---
•⁠  ⁠name: Deploy WAR from S3
  hosts: webservers
  become: yes

  tasks:
    - name: Download WAR file from S3
      amazon.aws.s3_object:
        bucket: "{{ BUCKET_NAME }}"
        object: "{{ ARTIFACT_NAME }}"
        dest: "/tmp/{{ ARTIFACT_NAME }}"
        mode: get
      delegate_to: localhost

    - name: Copy WAR file to Tomcat webapps directory
      ansible.builtin.copy:
        src: "/tmp/{{ ARTIFACT_NAME }}"
        dest: "/opt/tomcat/webapps/{{ ARTIFACT_NAME }}"
        remote_src: yes